server:
  port: 8080
spring:
  datasource:
    initialization-mode: always
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ruvik
    username: postgres
    password: postgres
